"""Solver-agnostic data model for the verification + allocation harness.

Every other harness module is written against these types, never against
NVARC's or RUN-001's field names directly (`adapters/` is the one place that
translation happens). That is the whole point of a wrapper: a solver swapped
in later (TRM, a diffusion model) only needs a new adapter, not changes to
`verifier/` or `allocator/`.

Frozen-baseline discipline: nothing in this module or its callers may read a
ground-truth field. Candidates and evidence carry only what a solver run
produces; correctness, when it is needed at all (metrics, not verification),
is passed in separately by the caller from a solutions file, exactly as
`src/analysis/candidate_headroom.py` already does.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum


@dataclass(frozen=True)
class Candidate:
    """One decoded grid for one (task, test_index), from one solver branch.

    `grid_sha1` is the join key used everywhere else in the harness (and
    already the join key `src/run001/archive.py` uses); `grid` is carried
    alongside it so features that need the actual cells do not have to look
    it up elsewhere.
    """

    task_id: str
    test_index: int
    grid: list[list[int]]
    grid_sha1: str
    solver_branch: str
    seed: int | None = None
    augmentation_key: str | None = None
    beam_score: float | None = None
    score_aug: tuple[float, ...] = ()
    score_aug_mean: float | None = None
    generation_order: int | None = None
    cumulative_task_s: float | None = None
    candidate_latency_s: float | None = None
    raw: dict = field(default_factory=dict)
    """Whatever the adapter's source schema had beyond the fields above,
    preserved so a feature written for one solver's extra fields can still
    reach them without widening this dataclass. Never read by generic code."""


@dataclass(frozen=True)
class SelectionRecord:
    """One solver's own frozen ranking of one candidate (by `grid_sha1`).

    Kept separate from `Candidate` because a candidate can be generated by one
    process and ranked by another (`INSTRUMENTATION_DIFF.md` cell 8 — NVARC's
    selection pass runs after and independently of generation).
    """

    task_id: str
    test_index: int
    grid_sha1: str
    rank: int
    selected: bool
    algorithm: str


@dataclass
class CandidateSet:
    """Every candidate and selection record for one (task_id, test_index)."""

    task_id: str
    test_index: int
    candidates: list[Candidate] = field(default_factory=list)
    selection: list[SelectionRecord] = field(default_factory=list)

    def unique_grid_shas(self) -> list[str]:
        seen: dict[str, None] = {}
        for candidate in self.candidates:
            seen.setdefault(candidate.grid_sha1, None)
        return list(seen)

    def candidates_for_grid(self, grid_sha1: str) -> list[Candidate]:
        return [c for c in self.candidates if c.grid_sha1 == grid_sha1]

    def frozen_selected(self, top_k: int = 2) -> list[str]:
        """grid_sha1s the solver's own selector marked selected, in rank order."""
        ranked = sorted(
            (r for r in self.selection if r.selected), key=lambda r: r.rank
        )
        return [r.grid_sha1 for r in ranked[:top_k]]


@dataclass
class TaskEvidence:
    """A `CandidateSet` plus every feature computed from it.

    `features` is a flat `{name: value}` map rather than nested per-module
    structure, because verifiers consume features by name regardless of which
    `features/` module produced them, and a flat map is what
    `sklearn`-style tabular fitting wants directly.
    """

    task_id: str
    test_index: int
    candidate_set: CandidateSet
    features_by_grid: dict[str, dict[str, float | None]] = field(default_factory=dict)
    """grid_sha1 -> {feature_name: value}. `None` means "not computable from
    this archive", not zero — callers must not silently impute it."""
    demo_pairs: list[tuple[list[list[int]], list[list[int]]]] | None = None
    """The task's (input, output) demonstration pairs, for verifiers that need
    task context beyond the candidate set (`verifier/consensus.py`'s
    transformation-consistency baseline). `None` when unavailable; those
    verifiers must degrade gracefully rather than raise."""
    test_input: list[list[int]] | None = None


@dataclass
class VerificationResult:
    """A verifier's output for one `TaskEvidence`. Never touches ground truth."""

    task_id: str
    test_index: int
    ranked_grid_shas: list[str]
    probability_correct: dict[str, float]
    """grid_sha1 -> estimated P(correct), from whatever the verifier is."""
    uncertainty: float
    """Higher means less confident overall about this test index's ranking."""
    confidence_margin: float
    """probability_correct of rank-1 minus rank-2. Small margin, low confidence."""
    supporting_signals: dict[str, float] = field(default_factory=dict)
    contradicting_signals: dict[str, float] = field(default_factory=dict)
    calibration_metadata: dict = field(default_factory=dict)
    feature_provenance: dict[str, str] = field(default_factory=dict)
    """feature_name -> which features/ module produced it, for audit trails."""
    verifier_name: str = ""

    def top_k(self, k: int = 2) -> list[str]:
        return self.ranked_grid_shas[:k]


@dataclass(frozen=True)
class BudgetSnapshot:
    """The candidate set as it stood after some amount of compute.

    RUN-001 did not emit explicit budget checkpoints, but every candidate
    record carries `generation_order` and `cumulative_task_s`
    (`src/run001/archive.py` schema, populated by the real notebook run,
    `experiments/RUN001/RESULTS.md`). `snapshots.py` reconstructs snapshots by
    replaying that real ordering, so `budget` here is either a compute-seconds
    figure or a generation-order cutoff, never fabricated finer than what the
    archive actually recorded.
    """

    task_id: str
    test_index: int
    budget: float
    candidate_shas: tuple[str, ...]
    budget_unit: str = "cumulative_task_s"


class AllocationAction(str, Enum):
    """What the allocator may ask for next. Values match Phase-1 spec exactly."""

    STOP = "STOP"
    MORE_NVARC = "MORE_NVARC"
    MORE_AUGMENTATIONS = "MORE_AUGMENTATIONS"
    MORE_TTT = "MORE_TTT"
    MORE_SEEDS = "MORE_SEEDS"
    RUN_TRM = "RUN_TRM"
    RUN_COMPLEMENTARY_SOLVER = "RUN_COMPLEMENTARY_SOLVER"


@dataclass
class AllocationDecision:
    """One allocator decision for one task, with the reasoning kept attached."""

    task_id: str
    action: AllocationAction
    expected_marginal_value: float
    estimated_cost_seconds: float
    reason: str = ""


@dataclass
class TaskState:
    """Everything the allocator needs about one task across its test indices."""

    task_id: str
    evidence: dict[int, TaskEvidence] = field(default_factory=dict)
    """test_index -> TaskEvidence"""
    verification: dict[int, VerificationResult] = field(default_factory=dict)
    """test_index -> VerificationResult"""
    compute_spent_seconds: float = 0.0
    stopped: bool = False
    action_history: list[AllocationAction] = field(default_factory=list)


@dataclass
class HarnessResult:
    """The harness's final, submission-ready output for one run."""

    task_states: dict[str, TaskState]
    submission: dict[str, list[dict[str, list[list[int]]]]]
    """task_id -> [{"attempt_1": grid, "attempt_2": grid}, ...], competition shape."""
    trace: list[dict] = field(default_factory=list)
    """Append-only decision log: one entry per allocator/verifier call, for
    provenance. Never trimmed; that is what makes a run auditable."""
    config_used: dict = field(default_factory=dict)
